name: Publish Container Images
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  push_to_registry:
    name: Build and push images to quay.io/hybridcloudpatterns
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io

      - name: Build and push latest image, for pushes
        if: ${{ github.ref_type != 'tag' }}
        run: make build

      - name: Build and push versioned image, for tags
        if: ${{ github.ref_type == 'tag' }}
        run: IMAGE_TAG=$GITHUB_REF_NAME make build
